Repository tomusborne/generatepress, pull requests merged in 2021-08, with the labels that each got.

#243 Fix unable to save new global colors
  inc/customizer.php
Labels: type: bug, priority: critical

#239 Dashboard redesign
  .eslintrc.json
  Gruntfile.js
  assets/css/admin/dashboard.css
  assets/css/admin/style.css
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-dashboard.css
  functions.php
  inc/class-dashboard.php
  inc/class-rest.php
  inc/dashboard.php
  package.json
  sass/dashboard.scss
  src/dashboard.js
  src/dashboard/go-pro/index.js
  src/dashboard/go-pro/pro-items.js
  src/dashboard/go-pro/style.scss
  src/dashboard/index.js
  src/dashboard/reset/index.js
  src/dashboard/reset/style.scss
  src/dashboard/start-customizing/customize-items.js
  src/dashboard/start-customizing/index.js
  src/dashboard/start-customizing/style.scss
  src/dashboard/style.scss
Labels: type: feature

#244 Change migration version
  inc/class-theme-update.php
Labels: type: chore

#245 Only load dashboard.js on main dashboard
  inc/class-dashboard.php
Labels: type: bug, priority: high

#247 Check for $post->ID in metabox registration
  inc/meta-box.php
Labels: type: bug, priority: medium

#230 Update changelog for 3.1.0
  readme.txt
Labels: type: chore

#249 Try typography migration
  .eslintrc.json
  composer.json
  functions.php
  inc/class-typography-migration.php
  inc/class-typography.php
  inc/customizer.php
  inc/customizer/controls/js/customizer-controls.js
  inc/customizer/helpers.php
  inc/plugin-compat.php
  inc/typography.php
Labels: type: feature, priority: high
