Repository tomusborne/generatepress, pull requests merged in 2021-07, with the labels that each got.

#205 Fix manual font family entry
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: bug

#201 Pass $type to the generate_typography_css_selector filter
  inc/class-typography.php
Labels: enhancement

#194 Fix the alignment of the with unit component
  assets/dist/style-customizer.css
  src/components/unit-picker/style.scss
Labels: enhancement

#204 Update the font weight values depending on your selected font
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/utils/get-font-weights/index.js
Labels: enhancement

#211 Load viewport tag earlier
  inc/structure/header.php
Labels: enhancement

#209 Feat/propagate font manager changes
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: enhancement

#213 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: priority: low, type: chore

#214 Add GitHub actions for PHP
  .github/workflows/php-ci.yml
Labels: priority: low, type: chore

#207 Integrate dynamic attributes
  404.php
  archive.php
  content-404.php
  content-link.php
  content-page.php
  content-single.php
  content.php
  footer.php
  functions.php
  header.php
  inc/class-html-attributes.php
  inc/plugin-compat.php
  inc/structure/archives.php
  inc/structure/comments.php
  inc/structure/footer.php
  inc/structure/header.php
  inc/structure/navigation.php
  inc/structure/post-meta.php
  inc/theme-functions.php
  index.php
  no-results.php
  page.php
  search.php
  sidebar-left.php
  sidebar.php
  single.php
Labels: type: feature

#212 Improve typography units
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/placeholders.js
Labels: priority: high, type: feature

#216 Fix font manager item z-index issue
  assets/dist/style-customizer.css
  src/customizer-controls/font-manager/style.scss
Labels: priority: medium, type: bug

#220 Improve typography propagation
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: priority: critical, type: bug

#219 Fix typography customizer double refresh
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/range-control/index.js
Labels: priority: high, type: bug

#218 Fix typography sanitize process
  inc/customizer.php
Labels: priority: critical, type: bug

#221 Clean up legacy color/typography functions
  inc/customizer/controls/js/customizer-controls.js
  inc/plugin-compat.php
Labels: type: chore

#222 Add Google font-display option
  assets/dist/style-customizer.css
  inc/class-typography.php
  inc/customizer.php
  inc/defaults.php
  src/style.scss
Labels: priority: high, type: feature

#223 Add Google font api version to font manager attributes
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  inc/customizer.php
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: type: feature

#224 Clean up legacy/unnecessary code
  inc/plugin-compat.php
Labels: type: chore

#226 Implement GeneratePressControl to reduce code duplication
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/GeneratePressControl.js
  src/customizer-controls/color-manager/GeneratePressColorManagerControl.js
  src/customizer-controls/color-manager/index.js
  src/customizer-controls/color-picker/GeneratePressColorControl.js
  src/customizer-controls/color-picker/index.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControl.js
  src/customizer-controls/font-manager/GeneratePressTypographyControl.js
  src/customizer-controls/font-manager/index.js
Labels: priority: high, type: feature

#227 Move pure functions to utils.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/utils.js
Labels: priority: high, type: feature

#225 Prepare for 3.0.4 release
  functions.php
  package.json
  readme.txt
  style.css
Labels: type: chore

#228 Split GeneratePressTypographyControlForm into smaller components
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/style-customizer.css
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/TypographyList.js
  src/customizer-controls/font-manager/TypographyList/Typography.js
  src/customizer-controls/font-manager/TypographyList/Typography/DeleteButton.js
  src/customizer-controls/font-manager/TypographyList/Typography/Label.js
  src/customizer-controls/font-manager/TypographyList/Typography/SettingsButton.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/CustomSelector.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/DeviceInputGroup.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/FontFamily.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/FontSize.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/FontWeight.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/LetterSpacing.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/LineHeight.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/MarginBottom.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/TargetElement.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/TextTransform.js
Labels: priority: high, type: feature

#229 Open the font/typography popover when adding an item
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
Labels: priority: high, type: feature

#233 Add typography groups
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/style-customizer.css
  inc/customizer.php
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/TypographyList.js
  src/customizer-controls/font-manager/TypographyList/Typography.js
  src/customizer-controls/font-manager/style.scss
  src/customizer-controls/font-manager/utils.js
Labels: priority: medium, type: feature

#235 Replace the typography popover with a dropdown
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/style-customizer.css
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
  src/customizer-controls/font-manager/TypographyList/Typography.js
  src/customizer-controls/font-manager/TypographyList/Typography/DeleteButton.js
  src/customizer-controls/font-manager/TypographyList/Typography/Label.js
  src/customizer-controls/font-manager/TypographyList/Typography/SettingsButton.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings.js
  src/customizer-controls/font-manager/style.scss
  src/utils/get-icon/index.js
Labels: type: feature

#236 Fix Cannot read property '__experimentalGetPreviewDeviceType' of null
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  package.json
  src/extend/responsive-classes/index.js
Labels: priority: high, type: bug

#238 Add utility classes for global colors
  inc/css-output.php
Labels: priority: high, type: bug
