Repository tomusborne/generatepress, pull requests merged in 2021-09, with the labels that each got.

#252 Fix typography manager state propagation
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
Labels: type: bug, priority: critical

#250 Fix visited link color control
  assets/dist/style-customizer.css
  inc/customizer/fields/body.php
  src/style.scss
Labels: type: bug, priority: medium

#251 Remove typography targets from list if already added
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  src/customizer-controls/font-manager/utils.js
Labels: type: bug, priority: medium

#253 Remove git hooks
  Gruntfile.js
  composer.json
Labels: type: chore

#254 Make back to top button smooth scroll filterable
  .eslintrc.json
  assets/js/back-to-top.js
  assets/js/back-to-top.min.js
  inc/general.php
Labels: type: feature, priority: low

#256 Apply all underline options to editor links
  assets/css/admin/block-editor.css
  inc/block-editor.php
Labels: type: bug, priority: medium

#255 Update post title block selectors in the editor
  inc/block-editor.php
  inc/class-typography.php
Labels: type: bug, priority: medium

#258 Prevent classes in generate_get_attr() from being overwritten
  inc/theme-functions.php
Labels: type: bug, priority: critical

#257 Remove margin-top from headings in the editor
  assets/css/admin/editor-typography.css
  sass/editor-typography.scss
Labels: type: bug, priority: critical

#259 Revert submenu cls changes
  assets/css/all.css
  assets/css/all.min.css
  assets/css/main.css
  assets/css/main.min.css
  assets/css/mobile.css
  assets/css/mobile.min.css
  assets/css/style.css
  assets/css/style.min.css
  inc/css-output.php
  readme.txt
  sass/layout/mobile/_mobile-flex.scss
  sass/layout/mobile/_mobile-float.scss
  sass/layout/navigation/_navigation-dropdowns.scss
  sass/layout/navigation/_sidebar-navigation.scss
Labels: type: bug

#261 Fix duplicated fonts on migrating to new typography system
  inc/class-typography-migration.php
Labels: type: bug, priority: critical

#262 Exclude src folder from package
  Gruntfile.js
Labels: type: chore

#263 Remove Query Loop block margin
  assets/css/all.css
  assets/css/all.min.css
  assets/css/main.css
  assets/css/main.min.css
  assets/css/style.css
  assets/css/style.min.css
  sass/layout/content/_post-content.scss
Labels: type: bug, priority: medium

#264 Add default theme styling to headings in editor
  assets/css/admin/editor-typography.css
  sass/editor-typography.scss
Labels: type: bug, priority: critical

#265 Add the color palette classes to the editor
  inc/block-editor.php
Labels: type: bug, priority: high

#266 Fix allow typography negative values for letter spacing and margin bottom
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  inc/customizer.php
  inc/customizer/helpers.php
  src/customizer-controls/font-manager/TypographyList/TypographySettings/MarginBottom.js
  src/customizer-controls/font-manager/placeholders.js
Labels: type: bug, priority: medium

#267 Make body font selector in the editor more specific
  inc/class-typography.php
Labels: type: bug, priority: critical

#268 Prevent Customizer refresh when opening Typography section
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
Labels: type: bug, priority: critical

#271 Remove Google Fonts validation to enable the toggle
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
  src/customizer-controls/font-manager/google-fonts.json
Labels: type: bug, priority: medium

#272 Release 3.1.0 alpha.2
  functions.php
  package.json
  readme.txt
  style.css
Labels: type: chore

#273 Add preconnect resource hint to Google fonts
  inc/class-typography.php
  inc/general.php
Labels: type: bug, priority: high

#277 Use get_the_archive_description()
  inc/structure/archives.php
  readme.txt
Labels: type: feature, priority: medium

#276 Fix global color kebab case
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  inc/customizer.php
  src/customizer-controls/color-manager/GeneratePressColorManagerControlForm.js
Labels: type: bug, priority: critical

#278 Release 3.1.0 alpha.3
  functions.php
  package.json
  style.css
Labels: type: chore

#279 Add hash to hex values
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/color-picker/index.js
  src/utils/get-icon/index.js
Labels: type: bug, priority: high

#280 Release 3.1.0-beta.1
  functions.php
  package.json
  style.css
Labels: type: chore
