Repository tomusborne/generatepress, pull requests merged in 2021-06, with the labels that each got.

#174 Implement color field groups
  inc/customizer/class-customize-field.php
  inc/customizer/fields/primary-navigation.php
Labels: enhancement

#180 Add full settings key to color group to allow override
  inc/css-output.php
  inc/customizer/class-customize-field.php
  inc/customizer/fields/primary-navigation.php
Labels: enhancement

#184 Improve Advanced Select to be more extendable
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/advanced-select/index.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: enhancement

#175 Add device-specific classes to the editor
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  inc/block-editor.php
  package.json
  src/block-editor.js
  src/extend/responsive-classes/index.js
Labels: enhancement

#181 Typography element advanced select
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  package.json
  src/components/advanced-select/index.js
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/placeholders.js
Labels: enhancement

#189 Fix wrong selectors for sub-menu hover and current text colors
  inc/customizer/fields/primary-navigation.php
Labels: bug

#190 Add generate_search_title_output filter
  inc/structure/archives.php
  search.php
Labels: enhancement

#192 Fix broken search button icon when using font icons
  assets/css/components/font-icons.css
  assets/css/components/font-icons.min.css
  sass/components/_font-icons.scss
Labels: bug

#197 Add action customize after controls
  inc/customizer.php
Labels: feature

#196 Tighten up global colors UI
  assets/dist/style-customizer.css
  src/customizer-controls/color-manager/style.scss
Labels: enhancement

#195 Increase AdvancedSelect component height
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/advanced-select/index.js
Labels: enhancement

#198 Feat/add panel redirect control
  inc/customizer.php
  inc/customizer/controls/class-redirect-control.php
  inc/customizer/customizer-helpers.php
Labels: feature

#199 Add sectionRedirect to GeneratePress_Customize_Field::add_title
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/title/GeneratePressTitleControlForm.js
  src/utils/get-icon/index.js
Labels: enhancement

#191 Optimize SVG icons
  inc/theme-functions.php
Labels: enhancement

#203 Fix typography custom selector
  inc/class-typography.php
Labels: bug

#202 Allow decimals in font sizes
  inc/customizer.php
Labels: enhancement
