Repository tomusborne/generatepress, pull requests merged in 2022-08, with the labels that each got.

#400 Tweak: Refactor color picker
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-customizer.css
  package-lock.json
  package.json
  src/components/color-picker/ColorPicker.js
  src/components/color-picker/GlobalColorPicker.js
  src/components/color-picker/components/ColorButton.js
  src/components/color-picker/components/PanelColorPicker.js
  src/components/color-picker/index.js
  src/components/color-picker/style.scss
  src/customizer-controls/color-manager/GeneratePressColorManagerControlForm.js
  src/customizer-controls/color-picker/GeneratePressColorControlForm.js
  src/customizer-controls/color-picker/style.scss
Labels: refactoring

#420 Tweak: Add block editor width filters
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  inc/block-editor.php
  src/extend/content-width/index.js
Labels: refactoring

#421 Fix: Back to top iOS double-click issues
  assets/js/back-to-top.js
  assets/js/back-to-top.min.js
  inc/css-output.php
  inc/structure/footer.php
Labels: bug

#411 Feature: Use CSS variables for button colors
  assets/css/admin/block-editor.css
  assets/css/all.css
  assets/css/all.min.css
  assets/css/main.css
  assets/css/main.min.css
  assets/css/style.css
  assets/css/style.min.css
  inc/block-editor.php
  inc/css-output.php
  inc/customizer/fields/buttons.php
  inc/general.php
  sass/components/_forms-flex.scss
  sass/components/_forms-float.scss
Labels: feature

#422 Feature: Add more typography options
  assets/dist/block-editor.asset.php
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  inc/class-typography.php
  inc/customizer.php
  src/customizer-controls/font-manager/GeneratePressTypographyControlForm.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/FontStyle.js
  src/customizer-controls/font-manager/TypographyList/TypographySettings/textDecoration.js
Labels: feature

#428 Tweak: Change Google Font label in Font Manager
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/customizer-controls/font-manager/GeneratePressFontManagerControlForm.js
Labels: feature
