Repository tomusborne/generatepress, pull requests merged in 2022-05, with the labels that each got.

#364 Refactor color manager
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  package-lock.json
  package.json
  src/components/color-picker/index.js
  src/customizer-controls/color-manager/GeneratePressColorManagerControlForm.js
  src/customizer-controls/color-manager/components/ColorsList.js
  src/customizer-controls/color-manager/components/buttons.js
  src/customizer-controls/color-manager/hooks/useColors.js
Labels: priority: high, type: refactoring

#366 Remove excess screen reader text from post navigation
  inc/class-html-attributes.php
  inc/structure/post-meta.php
Labels: type: bug, priority: critical

#368 Add live preview to global color changes
  inc/block-editor.php
  inc/css-output.php
  inc/customizer.php
  inc/customizer/controls/js/customizer-live-preview.js
Labels: type: feature

#372 Fix customizer link encoding
  inc/class-dashboard.php
Labels: bug

#367 Implement option to reorder global colors
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-customizer.css
  inc/block-editor.php
  inc/css-output.php
  inc/customizer.php
  inc/customizer/controls/js/customizer-live-preview.js
  package-lock.json
  package.json
  src/components/color-picker/ColorButton.js
  src/components/color-picker/ColorPicker.js
  src/components/color-picker/GlobalColorPicker.js
  src/components/color-picker/components/ColorInput.js
  src/components/color-picker/components/ColorPalette.js
  src/components/color-picker/components/PanelColorPicker.js
  src/components/color-picker/components/VariableNameInput.js
  src/components/color-picker/index.js
  src/components/dnd/DndItem.js
  src/components/dnd/DndList.js
  src/components/dnd/index.js
  src/customizer-controls/color-manager/GeneratePressColorManagerControlForm.js
  src/customizer-controls/color-manager/components/ColorPlaceholder.js
  src/customizer-controls/color-manager/components/ColorsList.js
  src/customizer-controls/color-manager/components/buttons.js
  src/customizer-controls/color-manager/style.scss
  src/utils/get-icon/index.js
  src/utils/reorder.js
Labels: feature

#377 Fix link underlines in the editor
  inc/block-editor.php
Labels: bug

#343 Use block editor settings styles
  inc/block-editor.php
  inc/class-typography.php
Labels: bug

#380 Add editor-only CSS to the block editor
  assets/js/admin/block-editor.js
  inc/block-editor.php
Labels: bug

#370 Fix google fonts with standalone number
  inc/class-typography.php
Labels: bug

#369 Fix woocommerce archive wrapper attributes
  inc/class-html-attributes.php
  inc/plugin-compat.php
Labels: bug

#331 Add generate_hint_type filter
  inc/general.php
Labels: feature

#379 Feat: Global colors improvements and re-order functionality
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-customizer.css
  inc/block-editor.php
  inc/css-output.php
  inc/customizer.php
  inc/customizer/controls/js/customizer-live-preview.js
  package-lock.json
  package.json
  src/components/color-picker/ColorButton.js
  src/components/color-picker/ColorPicker.js
  src/components/color-picker/GlobalColorPicker.js
  src/components/color-picker/components/ColorInput.js
  src/components/color-picker/components/ColorPalette.js
  src/components/color-picker/components/PanelColorPicker.js
  src/components/color-picker/components/VariableNameInput.js
  src/components/color-picker/index.js
  src/components/dnd/DndItem.js
  src/components/dnd/DndList.js
  src/components/dnd/index.js
  src/customizer-controls/color-manager/GeneratePressColorManagerControlForm.js
  src/customizer-controls/color-manager/components/ColorPlaceholder.js
  src/customizer-controls/color-manager/components/ColorsList.js
  src/customizer-controls/color-manager/components/buttons.js
  src/customizer-controls/color-manager/hooks/useColors.js
  src/customizer-controls/color-manager/style.scss
  src/utils/get-icon/index.js
  src/utils/reorder.js
Labels: feature
