Repository tomusborne/generatepress, pull requests merged in 2022-11, with the labels that each got.

#468 Fix: Unit picker popover position
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  src/components/unit-picker/index.js
Labels: bug

#471 Fix: Editor content width when using large content padding values
  assets/dist/block-editor.asset.php
  assets/dist/block-editor.js
  readme.txt
  src/extend/content-width/index.js
Labels: bug

#473 Tweak: Open sub-menus with spacebar
  assets/js/menu.js
  assets/js/menu.min.js
  readme.txt
Labels: feature

#474 Fix: Empty footer post meta
  inc/structure/post-meta.php
Labels: bug

#477 Fix: Color picker out of view in Customizer
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  readme.txt
  src/components/color-picker/index.js
Labels: bug

#481 Tweak: Improve color picker position
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-customizer.css
  inc/customizer/helpers.php
  src/components/color-picker/index.js
  src/components/color-picker/style.scss
  src/customizer-controls/color-picker/style.scss
Labels: bug

#478 Release: 3.2.3
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  assets/dist/style-customizer.css
  functions.php
  inc/customizer/helpers.php
  package.json
  readme.txt
  src/components/color-picker/index.js
  src/components/color-picker/style.scss
  src/customizer-controls/color-picker/style.scss
  style.css
Labels: release

#484 Fix: Kebab-case formatting for global colors variable names
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  readme.txt
  src/components/color-picker/GlobalColorPicker.js
Labels: bug

#483 Release: 3.2.4
  assets/dist/customizer.asset.php
  assets/dist/customizer.js
  assets/dist/dashboard.asset.php
  assets/dist/dashboard.js
  functions.php
  package.json
  readme.txt
  src/components/color-picker/GlobalColorPicker.js
  style.css
Labels: release
